### DISCUSSION TITLE
Markdown syntax support of <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Esc</kbd>

### DISCUSSION THREAD

**Discussion by whoimicom** [web-infra-dev/rspress#1261] [Q&A]
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Esc</kbd> 
目前按键语法不生效?

**Comment by Timeless0911** [comment]
This is the syntax of HTML. I tried it and it worked fine.

![image](https://github.com/user-attachments/assets/c1f219a1-8bb8-4756-8b0e-08e27758ded1)

**Reply by whoimicom** [reply]
RSPRESS中能正常显示,但加了KBD标签的跟没加的显示都一致,这不正常吧?
以下是其它MD文件的预览效果,目前RSPRESS中没有体现出来 

- <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Esc</kbd>
- Ctrl+Shift+Esc

**Reply by Timeless0911** [reply]
你可以查看你其他 html 文件中的 css，kbd 标签的样式跟随浏览器，当然你也可以自己定义，可以查看下 mdn 文档 https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd

**Reply by Timeless0911** [reply]
![image](https://github.com/user-attachments/assets/db46ae7a-f473-476e-8667-bc403241b902)

**Reply by Timeless0911** [reply]
rspress 的 kbd 样式跟随 tailwind css 的 preflight，也就是浏览器的默认配置

```css
/*
1. Use the user's configured `mono` font-family by default.
2. Use the user's configured `mono` font-feature-settings by default.
3. Use the user's configured `mono` font-variation-settings by default.
4. Correct the odd `em` font sizing in all browsers.
*/

code,
kbd,
samp,
pre {
  font-family: theme('fontFamily.mono', ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace); /* 1 */
  font-feature-settings: theme('fontFamily.mono[1].fontFeatureSettings', normal); /* 2 */
  font-variation-settings: theme('fontFamily.mono[1].fontVariationSettings', normal); /* 3 */
  font-size: 1em; /* 4 */
}
```
