### ISSUE TITLE
[Bug]: Features link in the homepage does not contain the base path

### ISSUE THREAD

**Issue by asurance** [web-infra-dev/rspress#1234]
### 版本信息

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i7-13620H
    Memory: 5.40 GB / 15.73 GB
  Browsers:
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.22621.3527


    "@modern-js/core": "2.54.5",
    "@modern-js/eslint-config": "2.54.5",
    "@modern-js/module-tools": "2.54.5",
    "@modern-js/plugin-rspress": "1.25.2",
```

### 问题详情

生成的主页中features模块对应的跳转链接没有带上配置的base

### 复现链接

https://github.com/asurance/openify

### 复现步骤

项目对应文档地址：https://asurance.github.io/openify/
![image](https://github.com/web-infra-dev/rspress/assets/23739401/1d0c5b23-b72a-4ebb-97bc-48bbb4bef652)
上方的hero区点击跳转正常，下方features点击跳转后会缺少base导致访问404(本地调试正常，部署后异常)
对应配置
```
hero:
  name: Openify
  actions:
    - theme: brand
      text: 欢迎使用
      link: /guide/intro/welcome
    - theme: alt
      text: 快速上手
      link: /guide/intro/getting-started

features:
  - title: 静态调用
    link: /guide/feature/static-call
  - title: Promise化
    link: /guide/feature/promisify
  - title: 组件库无关
```
