### ISSUE TITLE
[Bug]: The icon and img tags under features will be recognized as strings

### ISSUE THREAD

**Issue by slowlyo** [web-infra-dev/rspress#1582]
### Version

```sh
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 24.31 GB / 31.28 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  npmPackages:
    rspress: ^1.37.0 => 1.37.0
```

### 问题描述

下面是我原来的内容: 

```
features:
  - title: xxx
    icon: <img src="logo.png" alt="Laravel Logo" />
    details: xxx
```

这段内容在之前是可以正常渲染的, 今天在使用 github actions 自动部署之后, 我发现原本正常显示的图标显示成了字符串

翻看了一下源码, 发现是 `<img />` 标签没有被认定为 html 标签, 导致被渲染成了字符串

参照现在的代码逻辑, 我需要将内容替换为下面的形式, 来实现它应有的效果:

```
features:
  - title: xxx
    icon: <div><img src="logo.png" alt="Laravel Logo" /></div>
    details: xxx
```

### 产生问题的原因

翻看了一下对应文件的更新记录, 发现这个问题来自一次 PR:

[fix: render inline markdown with generic syntax](https://github.com/web-infra-dev/rspress/pull/1557) (#1557)

[对应的文件更改](https://github.com/web-infra-dev/rspress/commit/0b96073af3aefbcea469885f91e30580e74111bf#diff-3b3c40a4dde8f814c76d5e7b7ac9d36407dfa6360aa54c1628635b19a6612b3c)

### Reproduce link

null

### Reproduce Steps

null
