### ISSUE TITLE
[Bug]: inconsistent flexbox layout with odd number of features in home page

### ISSUE THREAD

**Issue by superwushu** [web-infra-dev/rspress#215]
### Version

```sh
1.1.1
```

### Details

It looks like the feature layout in the home page is not quite consistent. For example, 6 features as in the rspress.dev site yield a 3x2 flexbox. But 5 features as below yield a 1x6 layout, which looks bad:

```
---
pageType: home

hero:
  name: My Doc
  text: my doc
  tagline:
  actions:
    - theme: brand
      text: Get Started

features:
  - title: Feature 1
    details: feature 1
    icon: 📦
  - title: Feature 2
    details: feature 2
    icon: 📦
  - title: Feature 3
    details: feature 3
    icon: 📦
  - title: Feature 4
    details: feature 4
    icon: 📦
  - title: Feature 5
    details: feature 5
    icon: 📦
```
<img width="1258" alt="Screenshot 2023-10-19 at 23 48 52" src="https://github.com/web-infra-dev/rspress/assets/749998/38397f12-60f0-45ac-a882-e2db556d53f6">
I also tried other numbers: 7 for 1x7, 8 for 2x4 and 9 for 3x3, etc. Personally, I think 3xN looks nicer.

### Reproduce link

N/A

### Reproduce Steps

N/A
