### ISSUE TITLE
[Bug]: Duplicate CSS Styles and Unconverted Tailwind Identifiers on Official Website

### ISSUE THREAD

**Issue by sumy7** [web-infra-dev/rspress#551]
### Version

```sh
https://rspress.dev/
```

### Details

I've noticed an issue on the official website where the same CSS styles are being included twice. 
it appears that some Tailwind identifiers within the CSS have not been converted. 
![image](https://github.com/web-infra-dev/rspress/assets/3841747/d54d1f63-bd41-497a-945e-c17c496679ee)

### Reproduce link

https://rspress.dev/

### Reproduce Steps

1. visit https://rspress.dev/
2. open chrome devtools
3. search css selector `.menu`

**Comment by naoyashiga** [comment]
I have investigated this issue. The cause is still unknown.

# Reproduction environment

- My research environment is rspress version: 1.10.1
- This problem is reproduced only with rspress monorepo
    - The official rspress site is in packages/document. So the problem is happening on the official site
    - Reproduce in dev,prod
        - pnpm dev:website
        - pnpm build:website
- Reproduce with chrome,safari,firefox

# Problem Details

```ts
import './vars.css';
import './base.css';
import './code.css';
import './scrollbar.css';
```

The contents of [packages/theme-default/src/styles/index.ts](https://github.com/web-infra-dev/rspress/blob/main/packages/theme-default/src/styles/index.ts) is bundled twice.

```css
/*
This is the built index.css
The middle part is omitted. Only .menu is written.
 */
/* src/styles/base.css */

.menu {
  display: flex;
  align-items: center;
  justify-content: space-around;
  font-size: 0.875rem;
  line-height: 1.25rem;
  font-weight: 700;
}

/* #region "../theme-default/src/styles/base.css" */
.menu {
  @apply flex justify-around items-center text-sm font-bold;
}
```

The first time, the tailwind is built correctly.

The second time, the tailwind is not built and is output as is. So, the apply syntax is output to index.hash.css as it is.

# Suspected cause

There could be a problem caused by monorepo, I checked the Modern.js configuration file and I couldn't find the problem for me.
