### ISSUE TITLE
[Feature]: home page template image allow for src-set

### ISSUE THREAD

**Issue by zackarychapple** [web-infra-dev/rspress#893]
### What problem does this feature solve?

Modern web development allows for the use of both srcset for additional resolutions and formats.  

### What does the proposed API look like?

```yaml
 image:
    srcset: /docs-logo-1x.png 1x, /docs-logo-2x.png 2x, 
    alt: Docs Logo
```
